routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RegistersController;


Route::get('/', function () {
    return view('app');
});



Route::resource('admin', RegistersController::class);

Route::get('/getdata', [RegistersController::class, 'getRegisters'])->name('admin.getdata');

app/Models/Registers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Registers extends Model
{
    use HasFactory;

    protected $fillable = [ 
        'company_name', 
        'company_code', 
        'name', 
        'email', 
        'age', 
        'password',
        ];


}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/RegistersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Registers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Hash;



class RegistersController extends Controller
{

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('admin');
    }

    public function getRegisters(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get("start");
        $rowperpage = $request->get("length"); // Rows display per page

        $columnIndex_arr = $request->get('order');
        $columnName_arr = $request->get('columns');
        $order_arr = $request->get('order');
        $search_arr = $request->get('search');
        $min_age = $request->get('min');
        $min_age = 0;

        $columnIndex = $columnIndex_arr[0]['column']; // Column index
        $columnName = $columnName_arr[$columnIndex]['data']; // Column name
        $columnSortOrder = $order_arr[0]['dir']; // asc or desc
        $searchValue = $search_arr['value']; // Search value

        // Total records
        $totalRecords = Registers::select('count(*) as allcount')->count();
        $totalRecordswithFilter = Registers::select('count(*) as allcount')->where('name', 'like', '%' . $searchValue . '%')->count();

        // Fetch records
        $records = Registers::orderBy($columnName, $columnSortOrder)
            ->where('company_name', 'like', '%' . $searchValue . '%')
            ->orWhere('company_code', 'like', '%' . $searchValue . '%')
            ->orWhere('name', 'like', '%' . $searchValue . '%')
            ->orWhere('email', 'like', '%' . $searchValue . '%')
            ->skip($start)
            ->take($rowperpage)
            ->get();

        $data_arr = array();
        $sno = $start + 1;
        foreach ($records as $record) {
            $id = $record->id;
            $company_name = $record->company_name;
            $company_code = $record->company_code;
            $name = $record->name;
            $age = $record->age;
            $email = $record->email;
            $button = '<a class="btn btn-primary" href="' . route('admin.edit', $id) . '">Muuda</a>';

            $data_arr[] = array(
                "id" => $id,
                "company_name" => $company_name,
                "company_code" => $company_code,
                "name" => $name,
                "age" => $age,
                "email" => $email,
                "button" => $button
            );
        }

        $response = array(
            "draw" => intval($draw),
            "iTotalRecords" => $totalRecords,
            "iTotalDisplayRecords" => $totalRecordswithFilter,
            "aaData" => $data_arr
        );

        echo json_encode($response);
        exit;
    }

    public function apiRegister(Request $request) {

        $r = json_decode($request->data);

        $rules = array(
            'name'       => 'required|min:3|max:255',
            'email'      => 'required|email|unique:registers,email',
            'age' => 'required|date',
            'password' => 'min:6'
        );

        if ($r->company) {
            $rules['company_name'] = 'required';
            $rules['company_code'] = 'required|max:10';
        }

        $validator = Validator::make((array) $r, $rules);

        if ($validator->fails()) {

                return response()->json([
                    "errors" => $validator->errors()
                ], 201);

        } else {

            $register = new Registers;
            if ($r->company_name != '') $register->company_name = $r->company_name;
            if ($r->company_code != '') $register->company_code = $r->company_code;
            if ($r->name != '') $register->name = $r->name;
            if ($r->email != '') $register->email = $r->email; 
            if ($r->age != '') $register->age = $r->age;
            if ($r->password != '') $register->password = $r->password;

            $register->save();

            return response()->json([
                "message" => "Registreeritud"
            ], 201);

        }



    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //TODO: Add users from admin panel
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // get the shark
        $register = Registers::find($id);

        // show the edit form and pass the shark
        return View::make('admin.edit')
            ->with('register', $register);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        switch ($request->input('action')) {
            case 'delete':

                $register = Registers::find($id);
                $register->delete();

                return Redirect::to('admin')->with('status', 'Kasutaja kustutatud');

                break;

            case 'save':

                //TODO: Translate validator errors
                $rules = array(
                    'name'       => 'required',
                    'email'      => 'required|email',
                    'age' => 'required|integer'
                );
                $validator = Validator::make($request->all(), $rules);

                if ($validator->fails()) {
                    return Redirect::to('admin/' . $id . '/edit')
                        ->withErrors($validator);
                } else {
                    $register = Registers::find($id);
                    if ($request->get('cname') != '') $register->company_name = $request->get('cname');
                    if ($request->get('code') != '') $register->company_code = $request->get('code');
                    if ($request->get('name') != '') $register->name = $request->get('name');
                    if ($request->get('email') != '') $register->email = $request->get('email');
                    if ($request->get('age') != '') $register->age = $request->get('age');
                    if ($request->get('pass') != '') $register->password = Hash::make($request->get('pass'));

                    $register->save();

                    return Redirect::to('admin')->with('status', 'Kasutaja uuendatud');
                }

                break;

        }
    }
}

resources/views/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- jQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
   
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/searchbuilder/1.3.4/css/searchBuilder.dataTables.min.css">
    <script type="text/javascript" src="https://cdn.datatables.net/searchbuilder/1.3.4/js/dataTables.searchBuilder.min.js"></script>
   
</head>
<body>
    <br />
    <br />
    
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <button id="fbutton" class="btn btn-primary float-right" style="float: right; margin-bottom: 10px;">Veel filtreid</button>

                        <table id="extra-filters" border="0" cellspacing="5" style="display: none; margin-left: auto; margin-bottom: 5px;">
                            <tbody><tr>
                                <td>Minimum age:</td>
                                <td><input style="box-sizing: border-box;
                                    margin: 0;
                                    font-family: inherit;
                                    font-size: inherit;
                                    line-height: inherit;
                                    outline-offset: -2px;
                                    -webkit-appearance: textfield;
                                    border: 1px solid #aaa;
                                    border-radius: 3px;
                                    padding: 5px;
                                    background-color: transparent;
                                    margin-left: 3px;
                                    margin-bottom: 5px" type="text" id="min" name="min"></td>
                            </tr>
                            <tr>
                                <td>Maximum age:</td>
                                <td><input type="text" style="box-sizing: border-box;
                                    margin: 0;
                                    font-family: inherit;
                                    font-size: inherit;
                                    line-height: inherit;
                                    outline-offset: -2px;
                                    -webkit-appearance: textfield;
                                    border: 1px solid #aaa;
                                    border-radius: 3px;
                                    padding: 5px;
                                    background-color: transparent;
                                    margin-left: 3px;" id="max" name="max"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>
                                    <input type="checkbox" id="company" name="company" value="Company">
                                    <label for="company">&nbsp;&nbsp;Näita ainult firmasid</label>
                                </td>
                            </tr>
                        </tbody>
                    </table>


                    <table id='empTable' class="display" width='100%' style='width: 100%;'>
                        <thead>
                            <tr>
                                <td>ID</td>
                                <td>Firma nimi</td>
                                <td>Registrikood</td>
                                <td>Nimi</td>
                                <td>Vanus</td>
                                <td>Email</td>
                                <td></td>
                            </tr>
                        </thead>
                    </table>

            </div>
        </div>
    </div>
    <script type="text/javascript">


        //TODO: Fix filters other than search
        $.fn.dataTable.ext.search.push(function (settings, data, dataIndex) {
           
            if (
                $('#company').is(':checked') && data[2] != '' 
            ) {
                return true;
            }
            return false;
        });

        $.fn.dataTable.ext.search.push(function (settings, data, dataIndex) {

            var min = parseInt($('#min').val(), 10);
            var max = parseInt($('#max').val(), 10);
            var age = parseFloat(data[4]) || 0; // use data for the age column
        
            if (
                (isNaN(min) && isNaN(max)) ||
                (isNaN(min) && age <= max) ||
                (min <= age && isNaN(max)) ||
                (min <= age && age <= max)
            ) {
                return true;
            }
            return false;
        });

        $(document).ready(function(){

            $('#fbutton').click(function(){
                $( "#fbutton" ).toggle();
                $( "#extra-filters" ).toggle();
            });

          //TODO: Translate
          // DataTable
          var table = $('#empTable').DataTable({
             processing: true,
             serverSide: true,
             ajax: "{{route('admin.getdata')}}",
             columns: [
                { data: 'id' },
                { data: 'company_name' },
                { data: 'company_code' },
                { data: 'name' },
                { data: 'age' },
                { data: 'email' },
                { data: 'button' },
             ]
          });


                $('#min, #max').keyup(function () {
                    table.draw();
                });


        });

        
    </script>
    <br />
    <br />
</body>
</html>

resources/views/admin/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Kasutaja muutmine</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <br />
    <br />
    
<a href="{{ URL::to('admin') }}" class="btn btn-primary">Tagasi</a>
<br /><br />

<h1>{{ $register->name }} muutmine</h1>

<br />

@php
   foreach ($errors->all() as $error) {
        echo '<div class="alert alert-danger" role="alert">' . $error . '</div>';
    }
@endphp 


<form method="POST" action="{{ route('admin.update', $register->id) }}">
    @method('PUT')
    @csrf
    <div class="form-floating mb-3">
        <input type="text" id="cname" name="cname" class="form-control" placeholder="Firma nimi" value="{{ $register->company_name }}">
        <label for="name">Firma nimi</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" id="code" name="code" class="form-control"placeholder="Registrikood" value="{{ $register->company_code }}">
        <label for="name">Registrikood</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" id="name" name="name" class="form-control"placeholder="Nimi" value="{{ $register->name }}">
        <label for="name">Nimi</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" id="email" name="email" class="form-control"placeholder="Email" value="{{ $register->email }}">
        <label for="name">Email</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" id="age" name="age" class="form-control"placeholder="Vanus" value="{{ $register->age }}">
        <label for="name">Vanus</label>
    </div>
    <div class="form-floating mb-4">
        <input type="text" id="pass" name="pass"placeholder="Uus parool" class="form-control">
        <label for="name">Uus parool</label>
    </div>

    <button class="btn btn-primary me-3" type="submit" name="action" value="save">Salvesta kasutaja</button>
    <button class="btn btn-danger" type="submit" name="action" value="delete">Kustuta kasutaja</button>

</form>

</div>

<br />
<br />

</body>
</html>

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</head>

<body>

<div id="app">
    <App></App>
</div>

<script defer src="{{ mix('/js/app.js') }}"></script>
</body>

</html>